import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF7945AB),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFF0DBFF),
  onPrimaryContainer: Color(0xFF2C0050),
  secondary: Color(0xFF5451BA),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFE2DFFF),
  onSecondaryContainer: Color(0xFF0E006A),
  tertiary: Color(0xFF7945AB),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF0DBFF),
  onTertiaryContainer: Color(0xFF2C0050),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF1D1B1E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF1D1B1E),
  surfaceVariant: Color(0xFFE9DFEB),
  onSurfaceVariant: Color(0xFF4A454E),
  outline: Color(0xFF7C757E),
  onInverseSurface: Color(0xFFF6EFF4),
  inverseSurface: Color(0xFF322F33),
  inversePrimary: Color(0xFFDDB7FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF7945AB),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFDDB7FF),
  onPrimary: Color(0xFF480B79),
  primaryContainer: Color(0xFF602B91),
  onPrimaryContainer: Color(0xFFF0DBFF),
  secondary: Color(0xFFC3C0FF),
  onSecondary: Color(0xFF241B8A),
  secondaryContainer: Color(0xFF3C37A0),
  onSecondaryContainer: Color(0xFFE2DFFF),
  tertiary: Color(0xFFDDB7FF),
  onTertiary: Color(0xFF480B79),
  tertiaryContainer: Color(0xFF602B91),
  onTertiaryContainer: Color(0xFFF0DBFF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF1D1B1E),
  onBackground: Color(0xFFE7E1E5),
  surface: Color(0xFF1D1B1E),
  onSurface: Color(0xFFE7E1E5),
  surfaceVariant: Color(0xFF4A454E),
  onSurfaceVariant: Color(0xFFCCC4CE),
  outline: Color(0xFF968E98),
  onInverseSurface: Color(0xFF1D1B1E),
  inverseSurface: Color(0xFFE7E1E5),
  inversePrimary: Color(0xFF7945AB),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFDDB7FF),
);
